s = set()
n = input("ennter number 1:")
s.add(int(n))
n = input("ennter number 1:")
s.add(int(n))
n = input("ennter number 1:")
s.add(int(n))
n = input("ennter number 1:")
s.add(int(n))
n = input("ennter number 1:")
s.add(int(n))
n = input("ennter number 1:")
s.add(int(n))
n = input("ennter number 1:")
s.add(int(n))
n = input("ennter number 1:")
s.add(int(n))
print(s)

